export const gifts = [
  { id: "gift-1", name: "Baby Bottles Set", category: "feeding", price: 800 },
  { id: "gift-4", name: "Latex Pacifiers 2-Pack Size 1", category: "soothers", price: 249 },
  { id: "gift-2", name: "Pacifier Box (In Color Sage)", category: "soothers", price: 329 },
  { id: "gift-3", name: "Eufy Wearable Breast Pump S1", category: "feeding", price: 3999 },
  { id: "gift-5", name: "Plush Character Snuggle Pillow - Assorted", category: "soothers", price: 419.9 },
  { id: "gift-6", name: "Shnuggle Dreami Moses Basket and Stand", category: "sleep", price: 2800 },
  { id: "gift-7", name: "Shnuggle Dreami Quilted Moses Basket Mattress", category: "sleep", price: 699 },
  { id: "gift-8", name: "Snuggletime Comfort Safety Pod - Snow", category: "sleep", price: 649 },
  { id: "gift-9", name: "Royal 3-in-1 Swing & High Chair - Beige", category: "play", price: 4250 },
  { id: "gift-10", name: "The Lumi Seat 5-in-1 Multifunctional Baby Chair", category: "play", price: 1990 },
  { id: "gift-11", name: "Wooden Baby Play Gym Toys", category: "play", price: 800 },
  { id: "gift-12", name: "Kids Nappy Caddy", category: "nappy", price: 299 },
  { id: "gift-13", name: "Bumbo Changing Pad - Taupe", category: "nappy", price: 999.9 },
  { id: "gift-14", name: "Magic Heka L Diaper Bin - Beige", category: "nappy", price: 999 },
  { id: "gift-15", name: "Baby Laundry Basket", category: "nappy", price: 529 },
  { id: "gift-16", name: "Nanobebe Flexy Silicone Bottle 150ml - Grey Twin Pack", category: "feeding", price: 399.99 },
  { id: "gift-17", name: "Novelty Face Cloths", category: "clothing", price: 100 },
  { id: "gift-18", name: "Novelty Hooded Towel", category: "clothing", price: 179 },
  { id: "gift-19", name: "Muslin Hooded Towel", category: "clothing", price: 259 },
  { id: "gift-20", name: "Waterproof Baby Changing Pad", category: "travel", price: 100 },
  { id: "gift-21", name: "Momcozy KleanPal Pro Baby Bottle Washer - EU Plug", category: "feeding", price: 6000 },
  { id: "gift-22", name: "Bundled Baby Development Books", category: "travel", price: 850 },
  { id: "gift-23", name: "Bolsa Maternity Bag - Green", category: "travel", price: 1400 },
  { id: "gift-24", name: "Stainless Steel Flask", category: "clothing", price: 400 },
  { id: "gift-25", name: "Portable Baby Carrier Toddler Wrap - Multifunctional Shoulders (Khaki)", category: "travel", price: 550 },
  { id: "gift-26", name: "Bath Stand - Emerald Baby", category: "nappy", price: 1000 },
  { id: "gift-27", name: "Fringe Muslin Blanket", category: "clothing", price: 299 },
  { id: "gift-28", name: "Baby Nurture Deluxe Bottle Brush", category: "feeding", price: 145 },
  { id: "gift-29", name: "Momcozy On-The-Go Bundle: Portable Milk Warmer + 22oz Milk Cooler", category: "feeding", price: 2399 },
  { id: "gift-30", name: "Haakaa Electric Nail Care Set - Acorn", category: "clothing", price: 330 },
  { id: "gift-31", name: "Kids Nappy Caddy", category: "nappy", price: 299 },
  { id: "gift-32", name: "Night Light For Kids", category: "sleep", price: 1040 },
  { id: "gift-33", name: "Fisher-Price Soothe 'n Snuggle Otter Plush Musical Soother", category: "soothers", price: 769.9 },
  { id: "gift-34", name: "Momcozy Baby Nasal Aspirator", category: "feeding", price: 650 },
  { id: "gift-35", name: "Noola Closer2You Baby Carrier", category: "travel", price: 1700 },
  { id: "gift-36", name: "Car Interior Rearview Mirror - Cartoon Baby Safety Seat Viewing", category: "travel", price: 400 },
  { id: "gift-37", name: "Lulu Fleece Rocking Chair - Cream", category: "sleep", price: 2199 },
  { id: "gift-38", name: "Snookums Medical Starter Kit", category: "clothing", price: 179.9 },
  { id: "gift-39", name: "Mellon Moon Reversible Baby Play Mat - Cloud/Construction Town", category: "play", price: 2000 },
  { id: "gift-40", name: "Children's Illustrated Bible", category: "play", price: 1350 }
];
